variable "environment_prefix" {}
variable "region" {}
variable "prod_drg_dft_rt_id" {}
variable "prod_drg_id" {}
variable "prod_drg_rt_table_id" {}
variable "prod_hub_ha_private_subnet_cidr_block" {}
variable "prod_hub_mgmt_public_subnet_cidr_block" {}
variable "prod_hub_priv_sub_id" {}
variable "prod_hub_private_subnet_cidr_block" {}
variable "prod_hub_private_subnet_route_table_id" {}
variable "prod_hub_pub_sub_id" {}
variable "prod_hub_public_subnet_cidr_block" {}
variable "prod_hub_public_subnet_route_table_id" {}
variable "prod_hub_vcn_cmpt_id" {}
variable "prod_hub_vcn_id" {}
variable "prod_igw_id" {}
variable "ssh_public_key" {}
variable "tenancy_ocid" {}
variable "vm_display_name" {}
variable "vm_flex_shape_ocpus" {}
